### ISSUE TITLE
Put codestyle into ThirtyInch

### ISSUE THREAD

**Issue by StefMa** [grandcentrix/ThirtyInch#122]
Since we [open sourced](https://github.com/grandcentrix/androidcodestyle) our code style I think about to add it here.
We can add it together with a CONTRIBUTING.md ( 🤔 ) to Ti. We won't have conflicts or "rerange the code everytime" if third parties contribute anymore...

What do you think @passsy @rberghegger ❓

**Comment by passsy** [comment]
Agree, was already on my personal todo list.
The code style should be commited into the project.

**Comment by rberghegger** [comment]
Yes I agree as well and will take care of it.

**Comment by rberghegger** [comment]
I've just opened pull request #123 that adds this codestyle to the project.
