### ISSUE TITLE
TiPresenter.test() missing Javadoc

### ISSUE THREAD

**Issue by passsy** [grandcentrix/ThirtyInch#124]
Missing Javadoc, copy from `TiTestPresenter` header. https://github.com/grandcentrix/ThirtyInch/blob/master/thirtyinch/src/main/java/net/grandcentrix/thirtyinch/TiPresenter.java#L389

**Comment by baltuky** [comment]
Hi. Can I take up this one?

**Comment by StefMa** [comment]
Yeah. Sure 👍
