### ISSUE TITLE
Package thirtyinch-kotlin-coroutines not published

### ISSUE THREAD

**Issue by RiccardoM** [grandcentrix/ThirtyInch#190]
Currently, the package `thirtyinch-kotlin-coroutines` has not been published on Maven. Is it possible to fix this and make it available for download?

**Comment by StefMa** [comment]
Hey,

yeah sure.
I will plan this for the next week 👍

**Comment by StefMa** [comment]
I've just released [TI 0.9.5](https://github.com/grandcentrix/ThirtyInch/releases/tag/v0.9.5)
Have fun 🎉

**Comment by RiccardoM** [comment]
Thank you so much @StefMa!
