### ISSUE TITLE
Release for androidx

### ISSUE THREAD

**Issue by michaelborisov** [grandcentrix/ThirtyInch#200]
Hi there!
First of all, thank you for the great library.

I wanted to ask if it is done intentionally, that the latest available release is not yet using androidx Activities and Fragments?

**Comment by Schumi09** [comment]
Hello,

any update on this topic? Will this library be further maintained?

**Comment by lukaszkalnik** [comment]
Hi, sorry but the AndroidX release got a bit forgotten internally.

We have just released the 1.0.0 version with AndroidX support. Please test it and report any issues.
