### ISSUE TITLE
Isn't this backwards?

### ISSUE THREAD

**Issue by Nxt3** [grandcentrix/ThirtyInch#25]
I'm relatively new to MVP and the like--but with Mosby, it looks like I'd make a `Presenter` as an interface and fill it with methods I want to implement. 

With Ti, I'm implementing those methods in the Activity. 

Am I thinking about this wrong or am I doing something wrong?

**Comment by StefMa** [comment]
Yep, you are doing it wrong ☺️
I have never used Mosby but when I take a look into the [Hello Word example]  (http://hannesdorfmann.com/mosby/getting-started/) you can adopt it to 100% to Ti! 
You can also have a look into our [Hello World example](https://github.com/grandcentrix/ThirtyInch/tree/master/sample/src/main/java/net/grandcentrix/thirtyinch/sample) to get a feeling how to use Ti.

**Comment by Nxt3** [comment]
That's just it, in the Mosby example, the Activity is calling the implemented methods from the View via `presenter.callMethod()`. Whereas in the Ti example, the View methods are implemented in the Activity.

**Comment by passsy** [comment]
The sample of `Ti` isn't showing the full power (we are working on it). There are two kind of methods. Methods doing something with the view such as styling a `Toolbar` or setting text to a `TextView` should be part of the `Activity`. Those methods will be called (only) by the Presenter. The Presenter has logic when those methods should be called. Sadly, in the current sample, the logic in the Presenter is super small and basically non existent.
Another hint: If you required the `Context` or any kind of android `View`, put it into the `Activity`. When dealing with IO (databases and networking stuff) put it into the presenter.

**Comment by Nxt3** [comment]
Is there a better example somewhere? If I can't see a better example I'm going to have to use something else (which I don't want to do). :|

**Comment by passsy** [comment]
There are a few samples here on github. One of the best I found after a quick search is this here: https://github.com/Mavamaarten/MVPDemo_thirtyinch/tree/7d36935fcaf1436d3a975a86e65251671af2a721/app/src/main/java/com/icapps/mvp
