### ISSUE TITLE
Use DialogFragment?

### ISSUE THREAD

**Issue by Nxt3** [grandcentrix/ThirtyInch#32]
How can I go about using this Library with a DialogFragment? Since we have to extend `TiFragment` I can't extend `DialogFragment`.

Possibly a dumb question.

**Comment by BenedictP** [comment]
There is a PR for DialogFragments: https://github.com/grandcentrix/ThirtyInch/pull/20
Perhaps it's comming soon ;)

**Comment by StefMa** [comment]
There is now an `TiDialogFragment`. Will be shipped with the next release..
See https://github.com/grandcentrix/ThirtyInch/pull/42
