### ISSUE TITLE
Need method  manageSubscriptions(Subscription ...subscription) in RxTiPresenterSubscriptionHandler

### ISSUE THREAD

**Issue by ar-g** [grandcentrix/ThirtyInch#37]
For conciseness, it would be helpful to have method  manageSubscriptions(Subscription ...subscription) in RxTiPresenterSubscriptionHandler

**Comment by passsy** [comment]
Can you give me an example where this is useful?

**Comment by ar-g** [comment]
The point is to not write manageSubscription() 10 times in presenter in onAttachView. Though could be easily achieved manually but would be just nice to have such method in RxTiPresenterSubscriptionHandler.

**Comment by StefMa** [comment]
Fixed in #43 
Will be shipped with the next release
