### ISSUE TITLE
how to get an instance of the presenter when extend from TiActivity

### ISSUE THREAD

**Issue by wenjiahui** [grandcentrix/ThirtyInch#4]
In the demo, HelloWorldActivity extends TiActivity,  but I can't see any method to get the presenter instance.

**Comment by tzutolin** [comment]
Simply call getPresenter() I guess.

**Comment by jannisveerkamp** [comment]
As stated simply call `getPresenter()`. Make sure you are using Version `0.7.1`, since the method is missing in `0.7.0`.

**Comment by passsy** [comment]
duplicate #3
