### ISSUE TITLE
How to Inject Presenter Dependency to Activity ?

### ISSUE THREAD

**Issue by AruLNadhaN** [grandcentrix/ThirtyInch#41]
Hey, 
I'm trying to convert this [Library](https://github.com/hitherejoe/Bourbon) using ThirtyInch.

This is how my Presenter looks [like](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70)
This is the Original Library's [Presenter](https://github.com/hitherejoe/Bourbon/blob/master/CoreCommon/src/main/java/com/hitherejoe/bourboncorecommon/ui/browse/BrowsePresenter.java#L27). 

Now I have to inject the DataManager dependency in my Activity. This is my [BrowseActivity](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70). 

This is the Original Library's [BrowseFragment](https://github.com/hitherejoe/Bourbon/blob/6467d8db064f00a9e6614f63744e98982c353a9d/mobile/src/main/java/com/hitherejoe/bourbon/ui/browse/BrowseFragment.java#L40) (For Reference)

How can I inject the Dependency in the Activity or there is any workaround ?

**Comment by passsy** [comment]
Why aren't you using the Injection as it is [right now](https://github.com/hitherejoe/Bourbon/blob/6467d8db064f00a9e6614f63744e98982c353a9d/mobile/src/main/java/com/hitherejoe/bourbon/ui/browse/BrowseFragment.java#L57)? 

```java
public class BrowseFragment extends Fragment implements BrowseMvpView,
        BrowseAdapter.ClickListener {

    @Inject DataManager mDataManager;

    public BrowseActivity() {
        addPlugin(new TiActivityPlugin<BrowsePresenter, BrowseView>(
                () -> new BrowsePresenter(mDataManager)));
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        // call it before super.onCreate because providePresenter will be called there
        ((BaseActivity) getActivity()).activityComponent().inject(this);
        super.onCreate(savedInstanceState);
    }
```

Alternatively you can inject the dependencies directly into your Presenter. I normally use it like this:

```java

public class BrowsePresenter extends TiPresenter<BrowseView> {

    @Inject DataManager mDataManager;

    public BrowsePresenter() {
        App.component().inject(this).
    }

    // use this for your tests
    @VisibleForTesting
    BrowsePresenter(DataManager dataManager) {
        mDataManager = dataManager;
    }

}
```
```java
    // use constructor without arguments from the Activity
    public BrowseActivity() {
        addPlugin(new TiActivityPlugin<BrowsePresenter, BrowseView>(
                () -> new BrowsePresenter()));
    }
```

You have to make sure you can access the component statically somehow

**Comment by AruLNadhaN** [comment]
Thanks, I have injected the dependencies. But the interface method in the Presenter throws a NPE. 
`getView().showText("From PRESENTER!!!");`

[Updated Presenter code](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70)

**Comment by StefMa** [comment]
When is your `onViewReady` inside your acitivy called? 
If this method is called **before** `onAttachView` Fr the presenter, then it is your view null. 

You can by pass it via `sendToView` or call it after ` onAttachView`

**Comment by AruLNadhaN** [comment]
@StefMa `onViewReady` is called on the BaseActivity's  `Oncreate`
How can i call the `getProducts()` on the presenter before `onAttachView` ?

[Updated Base Activity](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70)

**Comment by passsy** [comment]
You don't want to call getProducts() from you Activity. Keep you Activity dumb. Instead call getProducts() from Presenter#onAttachView() because that's when the view will become visible to the user.

**Comment by AruLNadhaN** [comment]
If i call getProducts() from Presenter#onAttachView() then the mDataManager is null ? 

`java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Single me.arulnadhan.grocerycorecommon.data.DataManager.getProducts()' on a null object reference`

**Comment by passsy** [comment]
then your injection doesn't work

**Comment by AruLNadhaN** [comment]
mDataManager injection is working on the Activity. But it is not working on the Presenter.

Please take a look at the [Code](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70)

**Comment by passsy** [comment]
your `Activity#onCreate()` method is wrong. You're calling inject after `super.onCreate()`. At that time your presenter is already constructed. Use the code I recommended you above:

```java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        // call it before super.onCreate because providePresenter will be called there
        ((BaseActivity) getActivity()).activityComponent().inject(this);
        super.onCreate(savedInstanceState);
    }
```

**Comment by AruLNadhaN** [comment]
It works. Thanks a lot for the awesome library!
