### ISSUE TITLE
How to use sendToView ?

### ISSUE THREAD

**Issue by AruLNadhaN** [grandcentrix/ThirtyInch#57]
I'm trying to call a method in my View through `sendToView`. But it is not working ?
I have tried using `getView`. It returns NPE because i'm calling the `getProductsByCat` after the `Presenter onAttach`

```
public void getProductsByCat(String Category) {
//        final BrowseView view = getView();
        this.sendToView(BrowseView::showProgress);

        rxHelper.manageSubscription(
                RxFirebaseDatabase.observeValueEvent(mRef,
                        dataSnapshot -> {
                            List<Product> mProd = new ArrayList<>();
                            for (DataSnapshot postSnapshot : dataSnapshot.getChildren()) {
                                Timber.d("Count >>" + postSnapshot.getChildrenCount());
                                Product Prod = Product.create(postSnapshot);
                                mProd.add(Prod);
                            }
                            return mProd;
                        })
                        .subscribe(mProd -> {
                            Timber.d(mProd.get(0).productName());
                            sendToView(view -> {
                                view.hideProgress();
                                view.showText("Hello");
                                view.updateItems(mProd);
                            });
                        })
        );
    }
```

**Comment by StefMa** [comment]
Hey,
what are you trying?
`sendToView` wait's until the `view` got attached.
You can use it in your `onCreate` (for example):
`sendToView(view -> view.showProgress());`

`getView()` can cause a NPE when your view isn't attached yet to the `TiPresenter`.

> i'm calling the getProductsByCat after the Presenter onAttach

When do you call this method?

**Comment by AruLNadhaN** [comment]
I'm trying to load Items into my Recyclerview when the loading is completed in my Presenter. How can i Call `updateItems` from my Presenter ?

The onViewReady is called in the `Oncreate` after setContentView

```
public class BrowseActivity extends BaseActivity implements BrowseView, BrowseAdapter.ClickListener{

    @Inject
    DataManager mDataManager;
    @Inject
    BrowsePresenter mBrowsePresenter;

    BrowseAdapter mBrowseAdapter;
    @BindView(R.id.bmb)
    BoomMenuButton bmb;

 private final TiActivityPlugin<BrowsePresenter, BrowseView> mPresenterPlugin = new TiActivityPlugin<BrowsePresenter, BrowseView>(
            () -> new BrowsePresenter(mDataManager));

    public BrowseActivity() {
        addPlugin(mPresenterPlugin);
    }

    @Override
    protected void onViewReady(Bundle savedInstanceState, Intent intent) {
        super.onViewReady(savedInstanceState, intent);
        setupViews();
        assert bmb != null;
        bmb.setButtonEnum(ButtonEnum.TextInsideCircle);
        bmb.setPiecePlaceEnum(PiecePlaceEnum.DOT_9_1);
        bmb.setButtonPlaceEnum(ButtonPlaceEnum.SC_9_2);
        TextInsideCircleButton.Builder builder = new TextInsideCircleButton.Builder()
                        .normalImageRes(R.drawable.cat_beverages)
                        .normalText("Beverages")
                        .normalColorRes(R.color.orange)
                        .listener(new OnBMClickListener() {
                                @Override
                            public void onBoomButtonClick(int index) {
                                mBrowsePresenter.getProductsByCat(MYConstants.CAT_BEVERAGES);
                            }
                        });
                bmb.addBuilder(builder);
            }
}

 @Override
    public void updateItems(List<Product> items) {
        mBrowseAdapter.setNewData(items);
        mBrowseAdapter.notifyDataSetChanged();
        Timber.d("Adapter Count" + items.get(0).productName() + mBrowseAdapter.getData().size());
    }
```

**Comment by passsy** [comment]
Can you confirm onNext is called?

```
                    .subscribe(mProd -> {
                            Timber.d(mProd.get(0).productName());
                            sendToView(view -> {
                                view.hideProgress();
                                view.showText("Hello");
                                view.updateItems(mProd);
                            });
                        })
```


Either you are never calling `getProductsByCat(category)` or this Observable completes before it emits an item.

**Comment by AruLNadhaN** [comment]
I can [confirm ](https://github.com/nmoskalenko/RxFirebase/blob/0c88156f83af88e8ef6bfeaa1549f129d24dc696/rxfirebase/src/main/java/com/kelvinapps/rxfirebase/RxFirebaseDatabase.java#L24)that the onNext is called. I have also logged all the items from mProd. It is working as expected!

**Comment by passsy** [comment]
And your Activity is in foreground? Then the `sendToView` lambda should be called.

**Comment by AruLNadhaN** [comment]
Yeah. The Activity is in foreground. I even add a log statement in `sendToView`. It is also not executed :(

**Comment by passsy** [comment]
When you say `getView()` is `null` then the view is not attached. Either `onAttachView(view)` isn't called or `onDetachView()` is called already.
Add the `TiLogger` and post the output

```
TiLog.setLogger(TiLog.LOGCAT);
```

**Comment by AruLNadhaN** [comment]
This Log iscalled while the App is in foreground
`01-09 22:55:15.176 31529-31529/? V/ThirtyInch: BrowsePresenter:TiPresenter@3ae18bb: deprecated onWakeUp()`

These Logs are called when i Press home & comeback

```
01-09 22:58:28.056 31529-31529/? V/ThirtyInch: BrowsePresenter:TiPresenter@3ae18bb: deprecated onSleep()
01-09 22:58:28.056 31529-31529/? V/ThirtyInch: BrowsePresenter:TiPresenter@3ae18bb: onDetachView()
01-09 22:58:32.945 31529-31529/? V/ThirtyInch: TiActivityPlugin:TiActivity@1a4f10db:BrowseActivity@2f2f1778: binding the cached view to Presenter me.arulnadhan.shopper.activities.BrowseActivity@2f2f1778
01-09 22:58:32.945 31529-31529/? V/ThirtyInch: BrowsePresenter:TiPresenter@3ae18bb: onAttachView(TiView)
01-09 22:58:32.946 31529-31529/? V/ThirtyInch: BrowsePresenter:TiPresenter@3ae18bb: deprecated onWakeUp()
```

**Comment by AruLNadhaN** [comment]
If i use `manageViewSubscription` instead of `manageSubscription` . I get the below exception! 

`java.lang.IllegalStateException: view subscriptions can't be handled when there is no view at net.grandcentrix.thirtyinch.rx.RxTiPresenterSubscriptionHandler.manageViewSubscription(RxTiPresenterSubscriptionHandler.java:80) at me.arulnadhan.grocerycorecommon.ui.browse.BrowsePresenter.getProductsByCat(BrowsePresenter.java:59)`

**Comment by StefMa** [comment]
Can you please show your presenter code, **when** you call your `getProductsByCat()`❓❗️ 

Normally you have to use `manageViewSubscription` because you will destroy the subscription after your view got detached. That is the right behaviour.
It seems, however why, that the View don't get attached to the Presenter 🤔

**Comment by StefMa** [comment]
> Instead of calling getProductsByCat(category) from Activity. I moved it to onAttachView & used getView() instead of sendToView. It works perfectly.
> But Calling from Activity doesn't triggers getView or sendToView

So, wait what?! 
`getProductsByCat()` is business logic and have nothing todo inside your `Activity`.
So they right way **is** to have it inside the **Presenter**!

**Comment by AruLNadhaN** [comment]
When a Button is clicked on my Activity, I should change the products according to the category. So i should pass the Category ID to the Presenter in my Activity.

Please take a look at my gist  https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70#file-browseactivity-java-L34

**Comment by StefMa** [comment]
I'm I wrong or do you use two different Presenters? ;)
[First presenter](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70#file-browseactivity-java-L12)
[Second One](https://gist.github.com/AruLNadhaN/dc023c5854dab5000b73e800ae96fc70#file-browseactivity-java-L9)

You attach the First one to your `Activity` but call the `getProductsByCat()` to the second one. And the second one don't get attached to the `Activity`... 🤔  Right?

**Comment by StefMa** [comment]
I've created a short test and everything worked like expected.
-> https://gist.github.com/anonymous/111e6c4c50548503f46868731fb08d9f

**Comment by passsy** [comment]
You inject one Presenter and create another one in your Activity. Don't inject the Presenter and only use the one created from the plugin.

**Comment by AruLNadhaN** [comment]
Solved it! The problem is that i'm injecting another instance of presenter in my activity.

**Comment by AruLNadhaN** [comment]
@StefMa @passsy I recently changed my view code from Activity to Fragment. After the change, the String values are not retained. They always return NULL.

The string [Email](https://gist.github.com/AruLNadhaN/b0f89f94f153881f631f1b63d2645fde#file-browsepresenter-java-L90) returns the value here correctly.  But when it is [called ](https://gist.github.com/AruLNadhaN/b0f89f94f153881f631f1b63d2645fde#file-browsefragment-java-L39) from the Fragment. It always returns [NULL](https://gist.github.com/AruLNadhaN/b0f89f94f153881f631f1b63d2645fde#file-browsepresenter-java-L79)

**Comment by passsy** [comment]
Please ask those questions on Stackoverflow where you can get quick help from a bigger audience for your beginner questions.
Open issues here when you find bugs in the library, not bugs in your code.

**Comment by AruLNadhaN** [comment]
sorry. I thought that the values are not retained due to the library. Because it was working fine. When i was calling the presenter from the Activity.
