### ISSUE TITLE
Let manageSubscription(Subscription) return Subscription

### ISSUE THREAD

**Issue by passsy** [grandcentrix/ThirtyInch#59]
`RxTiPresenterSubscriptionHandler.manageSubscription(Subscription...)` returns void. It would be cool if there is a `manageSubscription` function with the following signature:

```java 
public Subscription manageViewSubscription(@NonNull final Subscription subscription)
```

Usage
```kotlin
// inside TiPresenter

val rxHelper: RxTiPresenterSubscriptionHandler(this)
val sub: Subscription? = null

/**
 * download some data
 */
fun download() {
    // subscription is managed, it will be cancelled when the Presenter gets destroyed
    sub = rxHelper.manageSubscription(myService.downloadSomething().subscribe{ data -> 
        sendToView { view -> view.showData(data) }
    })
}

/**
 * cancel download before it completes
 */
fun cancelDownload() {
    sub?.unsubscribe()
}
```

**Comment by StefMa** [comment]
Don't get the benefit here.
I can also first out the subscription to an field and then put it to the
`mangeSubscription`...
```java
mSub = Observable.stuff();
rxHelper.manageSub(mSub);
```

**Comment by passsy** [comment]
right now:

```java
mSub = someObservable.subscribe();
rxHelper.manageSubscription(mSub);
```

proposed:
```java
mSub = rxHelper.manageSubscription(someObservable.subscribe()) 
```
it saves one line of code 😄

**Comment by StefMa** [comment]
Does it any sense, with the current implementation?
I guess not.
We can only return an array of `Subscriptions` and then you have to extract it, after you put it into the `managerSubscriptions`.

**Comment by passsy** [comment]
of course we have to change the interface and add a new method. We can still change the public API because manageSubscription with varargs is only released in rc builds.

```java
// for single subscriptions
public Subscription manageSubscription(Subscription sub);

// for multiple
public void manageSubscriptions(Subscription... subs);
```
