### ISSUE TITLE
why not have onResume() &  onPause() in TiActivity

### ISSUE THREAD

**Issue by xiaomeixw** [grandcentrix/ThirtyInch#6]
RT....

**Comment by StefMa** [comment]
Have read the announcement on [medium](https://medium.com/@passsy/thirtyinch-a-new-mvp-library-for-android-bd1a27262fd6#.x60rk13vs)?
> callbacks for onResume/onPause are not supported because those lifecycle events should be handled in the View layer.

Take also a look into [this](http://hannesdorfmann.com/android/presenters-dont-need-lifecycle).

**Comment by xiaomeixw** [comment]
@StefMa OK，got it,Thanks....
