### ISSUE TITLE
Why use setRetainInstance(true) in TiFragment?

### ISSUE THREAD

**Issue by ar-g** [grandcentrix/ThirtyInch#67]
I do not fully understand why use` setRetainInstance(true)` in `TiFragment` by default. Since library always recovers presenter from `PresenterSavior`.

**Comment by passsy** [comment]
Yes, this is something which could be removed in the future

**Comment by passsy** [comment]
changed in [v0.8.0-rc4](https://github.com/grandcentrix/ThirtyInch/releases/tag/v0.8.0-rc4)
