### ISSUE TITLE
README improvements suggestion

### ISSUE THREAD

**Issue by stephanenicolas** [grandcentrix/ThirtyInch#7]
Hi TI team, while browsing through your README after you got mentioned in Android Dev Weekly, I would like to suggest a few improvements : 
- composition should be favored over inheritance, that should be the primary use case.
- we don't care much about dependencies, put this last.
- compare to other similar frameworks.
- link to a few MVP/MVVM resources.

**Comment by passsy** [comment]
Thanks stephan, I always appreciate your feedback! 

Have you read the introduction article on [medium](medium.com/@passsy/thirtyinch-a-new-mvp-library-for-android-bd1a27262fd6)? Did it make things clearer?

More in depth articles will follow, stay tuned

**Comment by stephanenicolas** [comment]
I update the original issue, nice article.
