### ISSUE TITLE
Gradle failed to sync with support library 24.2.1

### ISSUE THREAD

**Issue by tzutolin** [grandcentrix/ThirtyInch#8]
After upgrading to support library 24.2.1, the Android Studio 2.2(RC) reports "Failed to resolve: com.android.support:appcompat-v7:24.2.0". 

[build.gradle](https://github.com/grandcentrix/ThirtyInch/files/470958/build.gradle.zip)

**Comment by BenedictP** [comment]
Google deleted the 24.2.0 Version from the repos. But they will restore it: https://www.reddit.com/r/androiddev/comments/52m6ac/android_support_library_revision_2421_released/d7lptza

**Comment by tzutolin** [comment]
@BenedictP Thanks for your information.

**Comment by tzutolin** [comment]
As per Android Framework Team's [suggestion ](https://www.reddit.com/r/androiddev/comments/52m6ac/android_support_library_revision_2421_released/d7lptza), please consider support 24.2.1.

**Comment by li9ht** [comment]
```
def thirtyinchVersion = '0.7.1'
    compile ("net.grandcentrix.thirtyinch:thirtyinch:$thirtyinchVersion"){
        exclude group:"com.android.support"
    }
    compile ("net.grandcentrix.thirtyinch:thirtyinch-rx:$thirtyinchVersion"){
        exclude group:"com.android.support"
    }
    compile ("net.grandcentrix.thirtyinch:thirtyinch-plugin:$thirtyinchVersion"){
        exclude group:"com.android.support"
    }
    testCompile ("net.grandcentrix.thirtyinch:thirtyinch-test:$thirtyinchVersion"){
        exclude group:"com.android.support"
    }
```

this is what i did.. exclude the sopport lib from the lib ..

**Comment by StefMa** [comment]
Closed since https://github.com/grandcentrix/ThirtyInch/pull/11 is merged
